//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_User_roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B_User_roles()
        {
            this.A_UserLogin = new HashSet<A_UserLogin>();
        }
    
        public int RolesId { get; set; }
        public string Roles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_UserLogin> A_UserLogin { get; set; }
        public virtual B_User_roles B_User_roles1 { get; set; }
        public virtual B_User_roles B_User_roles2 { get; set; }
    }
}
