//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_address
    {
        public int UseraddressId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ConsigneeName { get; set; }
        public string UserPhone { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public string Detailedaddress { get; set; }
        public Nullable<int> Defaultstate { get; set; }
    }
}
