//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Commodity
    {
        public int CommodityId { get; set; }
        public string Tradename { get; set; }
        public string SubtitleofCommodity { get; set; }
        public Nullable<int> Commodityclassification { get; set; }
        public string CommodityDescription { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Contactnumber { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> Inventoryquantity { get; set; }
        public Nullable<int> Commoditycategory { get; set; }
        public string Image { get; set; }
    }
}
