//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_OrderXX
    {
        public int OrderxxId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public string Tradename { get; set; }
        public Nullable<System.DateTime> Ordertime { get; set; }
        public Nullable<int> PaymentmethodId { get; set; }
        public Nullable<double> Itempricing { get; set; }
        public string Commoditypictures { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UseraddressId { get; set; }
        public Nullable<int> Quantityofcommodities { get; set; }
        public Nullable<int> Orderstatus { get; set; }
    }
}
