//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Supplier
    {
        public int SupplierId { get; set; }
        public string Nameofsupplier { get; set; }
        public Nullable<int> Suppliertype { get; set; }
        public string SupplierTelephone { get; set; }
    }
}
