//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaTuErEntities1 : DbContext
    {
        public LaTuErEntities1()
            : base("name=LaTuErEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_UserLogin> A_UserLogin { get; set; }
        public virtual DbSet<B_User_roles> B_User_roles { get; set; }
        public virtual DbSet<C_Area> C_Area { get; set; }
        public virtual DbSet<D_address> D_address { get; set; }
        public virtual DbSet<E_Commodity> E_Commodity { get; set; }
        public virtual DbSet<F_Commoditypictures> F_Commoditypictures { get; set; }
        public virtual DbSet<G_Classification> G_Classification { get; set; }
        public virtual DbSet<I_Order> I_Order { get; set; }
        public virtual DbSet<J_OrderXX> J_OrderXX { get; set; }
        public virtual DbSet<K_ShoppingCart> K_ShoppingCart { get; set; }
        public virtual DbSet<L_Supplier> L_Supplier { get; set; }
        public virtual DbSet<M_Suppliertype> M_Suppliertype { get; set; }
        public virtual DbSet<N_Logisticscompany> N_Logisticscompany { get; set; }
        public virtual DbSet<O_Commodityinventory> O_Commodityinventory { get; set; }
    }
}
