//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaTuErEntities : DbContext
    {
        public LaTuErEntities()
            : base("name=LaTuErEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_UserLogin> A_UserLogin { get; set; }
        public virtual DbSet<B_User_roles> B_User_roles { get; set; }
        public virtual DbSet<E_Commodity> E_Commodity { get; set; }
        public virtual DbSet<F_Commoditypictures> F_Commoditypictures { get; set; }
        public virtual DbSet<G_Classification> G_Classification { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<J_OrderXX> J_OrderXX { get; set; }
        public virtual DbSet<O_Commodityinventory> O_Commodityinventory { get; set; }
    }
}
