//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chateau_Latour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class N_Logisticscompany
    {
        public int LogisticscompanyId { get; set; }
        public string NameofLogisticsCompany { get; set; }
        public string Logisticscompanycontacts { get; set; }
        public string Logisticstelephone { get; set; }
    }
}
